const defaultReports=[
 {id:'CP-2041',cat:'Facilities',title:'Air conditioning not working',loc:'Science Block · Lab 204',status:'In progress',time:'18 min ago',owner:'RK',mine:true,priority:'Normal'},
 {id:'CP-2038',cat:'Safety',title:'Loose handrail near staircase',loc:'Main Building · East Wing',status:'Urgent',time:'42 min ago',owner:'AM',mine:false,priority:'Urgent'},
 {id:'CP-2035',cat:'Cleanliness',title:'Bins need clearing after lunch',loc:'Central Cafeteria',status:'Resolved',time:'1 hr ago',owner:'NK',mine:false,priority:'Normal'},
 {id:'CP-2032',cat:'Tech',title:'Wi-Fi drops in study zone',loc:'Library · Ground Floor',status:'In progress',time:'2 hrs ago',owner:'IT',mine:true,priority:'Normal'},
 {id:'CP-2029',cat:'Facilities',title:'Projector cable is damaged',loc:'Lecture Hall B-12',status:'In progress',time:'3 hrs ago',owner:'RK',mine:false,priority:'Normal'},
 {id:'CP-2023',cat:'Safety',title:'Parking lights are off',loc:'North Parking',status:'Resolved',time:'Yesterday',owner:'AM',mine:false,priority:'Normal'}
];
let savedReports;try{savedReports=JSON.parse(localStorage.getItem('campusPulseReports')||'null')}catch{savedReports=null}let reports=Array.isArray(savedReports)?savedReports:defaultReports;let activeFilter='all',selectedCat='Facilities',selectedPriority='Normal';
const grid=document.querySelector('#report-grid'),myGrid=document.querySelector('#my-report-grid');
function statusClass(s){return s==='Resolved'?'resolved':s==='Urgent'?'urgent':''}function card(r,i){return `<article class="report-card" data-id="${r.id}" style="animation-delay:${i*.04}s"><div class="card-top"><span class="tag ${r.cat.toLowerCase()}">${r.cat.toUpperCase()}</span><span class="status ${statusClass(r.status)}">${r.status}</span></div><h3>${r.title}</h3><p class="loc"><i class="fa-solid fa-location-dot"></i>${r.loc}</p><div class="card-bottom"><span>${r.time}</span><span class="assigned"><span class="avatar">${r.owner}</span>Assigned</span></div></article>`}
function tracker(r){const resolved=r.status==='Resolved',progress=r.status==='In progress'||r.status==='Urgent',supported=(r.supporters||0)>0;document.querySelector('#detail-content').innerHTML=`<div class="detail-head"><h2>${r.title}</h2><p><i class="fa-solid fa-location-dot"></i> ${r.loc} &nbsp;·&nbsp; ${r.id}</p></div><div class="tracker-status"><span>LIVE STATUS</span><strong>${r.status}</strong></div><div class="timeline"><div class="timeline-item done"><b>Report received</b><p>${r.time} · Your voice is on the map.</p></div><div class="timeline-item ${progress||resolved?'done':'current'}"><b>Assigned to Campus Operations</b><p>Facilities coordinator has been notified.</p></div><div class="timeline-item ${resolved?'done':progress?'current':''}"><b>${resolved?'Issue resolved':'Work in progress'}</b><p>${resolved?'The team marked this report complete.':'You’ll see the next update here.'}</p></div></div><div class="owner-row"><span class="avatar">${r.owner}</span><span><strong>Campus Operations</strong>Accountable team owner</span></div><button class="support-btn ${supported?'active':''}" id="support-btn" data-id="${r.id}"><i class="fa-solid fa-user-plus"></i> ${supported?'You support this report':'I’m affected too'} <span>${r.supporters||0?`· ${r.supporters} supporters`:''}</span></button>`;document.querySelector('#detail-layer').classList.add('show');document.querySelector('#support-btn').onclick=()=>{if(!r.supporters){r.supporters=1;localStorage.setItem('campusPulseReports',JSON.stringify(reports));tracker(r);showToast('Support added — this helps prioritize the fix.')}else showToast('Your support is already counted.')}}
function render(){const query=document.querySelector('#search').value.toLowerCase();let list=reports.filter(r=>(activeFilter==='all'||(activeFilter==='urgent'?r.status==='Urgent':activeFilter==='progress'?r.status==='In progress':r.status==='Resolved'))&&(r.title+r.loc+r.cat).toLowerCase().includes(query));grid.innerHTML=list.length?list.map(card).join(''):'<div class="empty-state"><i class="fa-solid fa-magnifying-glass"></i>No matching reports yet.<br>Try another filter or make the first report.</div>';myGrid.innerHTML=reports.filter(r=>r.mine).map(card).join('')||'<div class="empty-state"><i class="fa-regular fa-flag"></i>No reports yet — your voice starts the change.</div>';document.querySelector('#open-count').textContent=Math.max(0,reports.filter(r=>r.status!=='Resolved').length);document.querySelectorAll('.report-card').forEach(el=>el.onclick=()=>tracker(reports.find(x=>x.id===el.dataset.id)))}render();
document.querySelectorAll('.filter').forEach(b=>b.onclick=()=>{document.querySelectorAll('.filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');activeFilter=b.dataset.filter;render()});document.querySelector('#search').oninput=render;
const modal=document.querySelector('#modal-layer');document.querySelectorAll('.report-trigger').forEach(b=>b.onclick=()=>modal.classList.add('show'));document.querySelector('.close-modal').onclick=closeModal;document.querySelector('.close-success').onclick=closeModal;modal.onclick=e=>{if(e.target===modal)closeModal()};function closeModal(){modal.classList.remove('show');setTimeout(()=>{document.querySelector('#form-state').style.display='block';document.querySelector('#success-state').classList.remove('show');document.querySelector('#report-form').reset();document.querySelector('#char-count').textContent='0'},200)}
document.querySelectorAll('.category').forEach(b=>b.onclick=()=>{document.querySelectorAll('.category').forEach(x=>x.classList.remove('active'));b.classList.add('active');selectedCat=b.dataset.category});document.querySelectorAll('.priority').forEach(b=>b.onclick=()=>{document.querySelectorAll('.priority').forEach(x=>x.classList.remove('active'));b.classList.add('active');selectedPriority=b.dataset.priority});document.querySelector('#details').oninput=e=>document.querySelector('#char-count').textContent=e.target.value.length;
document.querySelector('#report-form').onsubmit=e=>{e.preventDefault();const detail=document.querySelector('#details').value.trim(),loc=document.querySelector('#location').value.trim();const n={id:'CP-'+(2048+reports.length),cat:selectedCat,title:detail.length>48?detail.slice(0,48)+'…':detail,loc,status:selectedPriority==='Urgent'?'Urgent':'In progress',time:'Just now',owner:selectedCat==='Tech'?'IT':'RK',mine:true,priority:selectedPriority};reports.unshift(n);localStorage.setItem('campusPulseReports',JSON.stringify(reports));document.querySelector('#ticket-id').textContent=n.id;document.querySelector('#form-state').style.display='none';document.querySelector('#success-state').classList.add('show');let health=+document.querySelector('#health-score').textContent;document.querySelector('#health-score').textContent=Math.max(78,health-1);document.querySelector('.health-bar i').style.width=Math.max(78,health-1)+'%';render()};document.querySelector('.close-detail').onclick=()=>document.querySelector('#detail-layer').classList.remove('show');document.querySelector('#detail-layer').onclick=e=>{if(e.target===document.querySelector('#detail-layer'))document.querySelector('#detail-layer').classList.remove('show')};
const titles={dashboard:'Good morning, Shubh',reports:'My reports',explore:'Campus feed',insights:'Campus insights'};document.querySelectorAll('.nav-link').forEach(a=>a.onclick=()=>{document.querySelectorAll('.nav-link').forEach(x=>x.classList.remove('active'));a.classList.add('active');document.querySelectorAll('.view').forEach(v=>v.classList.remove('active-view'));document.querySelector('#'+a.dataset.view+'-view').classList.add('active-view');document.querySelector('#page-title').innerHTML=titles[a.dataset.view]+(a.dataset.view==='dashboard'?' <span>✦</span>':'');document.querySelector('.sidebar').classList.remove('open')});document.querySelector('#see-all').onclick=()=>document.querySelector('[data-view="explore"]').click();document.querySelector('.mobile-menu').onclick=()=>document.querySelector('.sidebar').classList.toggle('open');
document.querySelector('#feed').innerHTML=[['fa-circle-check','Facilities team resolved the cafeteria bin request','12 min ago'],['fa-wrench','Maintenance started work in Lab 204','24 min ago'],['fa-user-group','Three students supported the parking-light report','1 hr ago'],['fa-bolt','New hotspot identified: Science Block','2 hrs ago']].map(x=>`<article class="feed-item"><span class="feed-icon"><i class="fa-solid ${x[0]}"></i></span><p><strong>${x[1]}</strong><br>Making campus better, together.</p><time>${x[2]}</time></article>`).join('');
function showToast(msg){const t=document.querySelector('#toast');t.querySelector('span').textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2400)}const noticePanel=document.querySelector('#notice-panel');document.querySelector('.icon-btn').onclick=e=>{e.stopPropagation();noticePanel.classList.toggle('show')};document.querySelector('#clear-notices').onclick=()=>{noticePanel.classList.remove('show');document.querySelector('.icon-btn b').style.display='none';showToast('Notifications marked as read.')};document.addEventListener('click',e=>{if(!noticePanel.contains(e.target)&&!e.target.closest('.icon-btn'))noticePanel.classList.remove('show')});document.addEventListener('keydown',e=>{if(e.key==='Escape'){closeModal();document.querySelector('#detail-layer').classList.remove('show');document.querySelector('.sidebar').classList.remove('open');noticePanel.classList.remove('show')}})
